### ISSUE TITLE
Tailwind classes not applying to icons

### ISSUE THREAD

**Issue by SleeplessOne1917** [bbstilson/leptos_heroicons#2]
I'm trying to use tailwind classes to style icons imported from this library and it's not working. There is a small reproducible project  [here](https://github.com/LemmyNet/lemmy-ui-leptos/tree/hero-icons). You will see the issue with the style not applying to the bell icon in the nav component.

I'm not sure if this is a problem with my setup or the library. Help would be appreciated.

**Comment by bbstilson** [comment]
Hmm. I'm using tailwind and these icons in a personal project. I also ran into issues getting tailwind working though. Here are some steps I used to track down the issue. 

I would check the dom inspector to see that the classes are being applied. If they are, but aren't being styled as expected, then it's a problem with tailwind itself not being loaded properly. 

Another thing I used in debugging was the cdn script from tailwind rather than the build process.

Those two steps will help you narrow down the issue. 

Something I ran into specifically with leptos and tailwind was ensuring the file outputted by tailwind was being mapped to the expected location by leptos. This configuration is I'm the cargo toml and also the root application.

**Comment by SleeplessOne1917** [comment]
> I would check the dom inspector to see that the classes are being applied. If they are, but aren't being styled as expected, then it's a problem with tailwind itself not being loaded properly.

The classes were being applied, so it seems to be an issue with tailwind being loaded.

> Another thing I used in debugging was the cdn script from tailwind rather than the build process.

The styles applied correctly when I used the CDN.

> Something I ran into specifically with leptos and tailwind was ensuring the file outputted by tailwind was being mapped to the expected location my leptos. This configuration is I'm the cargo toml and also the root application.

It seems to be mapped correctly as tailwind styles apply to other elements. It's only the leptos hero icons that they don't work on.

**Comment by SleeplessOne1917** [comment]
I fixed the issue on my end. I had to run tailwind and cargo leptos in watch mode at the same time.
